<?php

namespace Sulphur;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-11-18 at 14:39:05.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Response
	 */
	protected $response;

	protected function setUp() {
		$factory = new ResponseFactory;
		$this->response = $factory->fromString(file_get_contents(__DIR__.'/data/reference.ini'));
	}

	/**
	 * @covers Sulphur\Response::where
	 */
	public function testWhere() {
		$this->assertInstanceOf('Sulphur\FilterableList', $this->response->where('foo'));
	}

	/**
	 * @covers Sulphur\Response::all
	 */
	public function testAll() {
		$this->assertInstanceOf('Sulphur\FilterableList', $this->response->all());
	}

}
